### ISSUE TITLE
Use as a simple DOM creation library

### ISSUE THREAD

**Issue by niahoo** [domvm/domvm#199]
Hello,

This is kind out of scope, but as I already use domvm for some projects, I would like to use it in another project where I do not need to mount anything, just create DOM elements and then return them from my functions.

Could dmvm be used in this way ? Like

```
return el('div', {onclick: handleClick}).toDomElement()
```

Something like that : https://github.com/KoryNunn/crel (which is what I currently use).

Thank you.

**Comment by leeoniya** [comment]
hey @niahoo ,

i recommend that you continue to use `crel` for this purpose, it looks minimal enough.

domvm's factories create vnodes, which in turn get processed to also create dom elements and then link the two bi-directionally via `vnode.el` and `el._node`. it would be hugely wasteful to create, preprocess and hydrate an entire vtree simply to then collect the dom off of it and throw the rest of the data structure away.

if you're really intent on it, domvm does expose its VNode and ViewModel prototypes [1], so you can always add fluent methods to those that walk the created (but non-hydrated) vtree and do something similar to `crel`, but that just seems silly.

hope that helps :)

[1] https://github.com/domvm/domvm/blob/3.x-dev/dist/pico/domvm.pico.js#L1542-L1543

**Comment by niahoo** [comment]
Hey !

Thanks, I understand that domvm does lots of work behind, that would be thrown away. So yeah,  `crel` will be fine :)
