### ISSUE TITLE
intent to remove event delegation

### ISSUE THREAD

**Issue by leeoniya** [domvm/domvm#200]
This is part PSA, part request for feedback,

I'd like to remove built-in support for event delegation eg:

```js
el("div", {onclick: {".foo": handeClick}})
```

There are several reasons for this and some subtle changes in fancy event behavior that would be involved. One motivation for this is lib simplification and size reduction, another is performance.

First, it's trivial to DIY event delegation in userland:

```js
function handleClick(e) {
  if (e.target.matches(".foo")) {
    // ...
  }
}

el("div", {onclick: handeClick})
```

Second, it's usually used as an optimization technique at the expense of clarity (adding listeners directly to many descendant elements). However, it turns out that this optimization is possible to do automatically in a vdom lib. The idea is to bind a single, document-level listener that then fires any defined `click` handlers. This document-level listener is bound in the `capturing` phase to ensure non-bubbling events like `focus` and `blur` can still be triggered. In turn, this means that any kind of "bubbling" up the dom must be simulated, including changing of `e.currentTarget` and all the other stuff the browser would do natively (which re-adds code and complexity).

In my experience, it is usually sufficient to trigger the first found handler in the dom hierarchy and stop, without simulating full bubbling behavior or modifying `e.currentTarget`, etc.

To be clear, this is only a modification to how fancy listeners will function (now only parameterized): `el("div", {onclick: [handler, arg1, ...]})`. The behavior of plain handlers will remain native and unchanged: `el("div", {onclick: handler})`.

The performance boost and mem reduction are quite good when thousands of listeners are involved - it's like getting event delegation for free.

comments, concerns?

cc @lawrence-dol @foxdonut @tropperstyle @iamjohnlong

**Comment by iamjohnlong** [comment]
@leeoniya sounds good to me.

**Comment by lawrence-dol** [comment]
It sounds good to me too.

I didn't even realize this was possible. Even though I frequently handle some events at the container level, particularly with lists I wouldn't have found this feature especially useful anyway. I also don't like the decreased clarity; it's too obscure for my taste.

On a related note, it sounds like DOMVM does special handling for parameterized events ("fancy" events); I'm a little surprised that these are not simply wrapped by a function that builds the argument list and invokes the handler (and therefore have no special event propagation considerations).

**Comment by tropperstyle** [comment]
I've never used the event delegation syntax, so no attachments here. Tangential request: shouldn't fancy handlers be invoked with the original context of `this`?

**Comment by leeoniya** [comment]
> On a related note, it sounds like DOMVM does special handling for parameterized events

the primary reason is performance. the only cost incurred during vtree rebuilds is array allocation as opposed to:

1. array allocation
2. recreating a handler
2a. ...but only after diffing the array to make sure the params haven't changed between redraws.
3. re-binding the listener

instead, we simply grab `e.target._node.attrs["on" + e.type]` and execute the handler at event-time with any needed args. thus, no event param diffing and no extra closured handlers. additionally, by handling it all in a single document-level capturing listener, there isnt even any event binding overhead, so `O(1)`. this also saves memory and could reduce possible mem leaks.

> Tangential request: shouldn't fancy handlers be invoked with the original context of `this`?

for uniformity's sake, domvm sets `this === vm`. original this can still be had for raw listeners: `{onclick: handler}`. use of `this` is generally discouraged in domvm anyhow, but i'd rather be consistent either way.

**Comment by leeoniya** [comment]
thanks for your input, guys. v3.4.0 is published with this change and other improvements.
