### ISSUE TITLE
prop drilling / createContext

### ISSUE THREAD

**Issue by leeoniya** [domvm/domvm#202]
So, https://daveceddia.com/context-api-vs-redux/ got me thinking about how something like this can be supported in domvm.

After experimenting with a couple implementations (and dead ends), i settled on a simple minor addition: a `newParent` arg for `render(vm, data, key, newParent, newIdx)`. This allows for anything inside `render()` to walk up the partially-constructed vtree and pull anything from it.

Here's an example of what you can now do in app-space to pull data out of ancestor views and/or vnodes.

https://jsfiddle.net/s9cz2wu3/

This does not include any facility for auto-optimizing render via diff/shouldComponentUpdate as redux would do, but it does solve the prop-drilling issue concisely without resorting to globals or an additional state management solution.

I don't plan to implement `VNode.prototype.pull` in the core, so I feel like this should go into the wiki with a mention and link from the docs.

thoughts?

cc @lawrence-dol @iamjohnlong @tropperstyle @foxdonut

```js
domvm.VNode.prototype.pull = function(key) {
    var node = this;

    // walk up the vtree, searching any data on vnodes & vms
    while (node != null) {
        var vm = node.vm;
        var data = vm != null ? vm.data : node.data;

        if (data != null && key in data)
            return data[key];

        node = node.parent;
    }
};

const el = domvm.defineElement;
const vw = domvm.defineView;
const cv = domvm.createView;

function App() {
    return () =>
        el("div", [
            vw(Header)
        ]);

}

function Header() {
    return () =>
        el("div", [
            vw(UserInfo)
        ]);
}

function UserInfo(vm) {
    return (vm, data, key, newPar) => {
        return el("strong", newPar.pull("user").name);
    }
}

const data = {
    user: {
        name: "Leon",
    }
};

cv(App, data).mount(document.body);
```

**Comment by iamjohnlong** [comment]
Would this be problematic if you have two data sets/components with the same `user` property?

**Comment by leeoniya** [comment]
can you give an example?

**Comment by lawrence-dol** [comment]
That seems like a reasonable approach to take. 

I definitely agree that `pull` does not belong in the core -- it's trivial and the kind of thing that causes unnecessary library bloat.
