### ISSUE TITLE
TypeError: d.firstChild is null

### ISSUE THREAD

**Issue by lawrence-dol** [domvm/domvm#203]
I am working on a problem that seems to be introduced by a relatively new build of DOMVM, meaning the code used to work without issue. The symptom is the type error in the subject. 

I have not gotten to the point of a fiddle yet since I have no clue yet how to replicate the fault outside of the context of my app. **All I am looking for at this point is suggestions** for the kind of mistake or fault I could make that could cause the firstChild property to be unexpectedly null when patching.

If it helps, it seems to only happen when the display is recreated, but unchanged.

It happens in patch, here:

		else {
			// "" | null => []
			if (newIsArr) {
				clearChildren(donor);
				hydrateBody(vnode);
			}
			// "" | null => "" | null
			else if (nbody !== obody) {
				if (nbody != null && obody != null)
					{ el.firstChild.nodeValue = nbody; } // <== el.firstChild is null
				else
					{ el.textContent = nbody; }
			}
		}

The stacktrace is:

`````
TypeError: el.firstChild is null, can't access property "nodeValue" of it[Learn More] AppScript:1498:8
	patch https://localhost/jse/AppScript:1498:8
	patchChildren https://localhost/jse/AppScript:1605:7
	patch https://localhost/jse/AppScript:1480:7
	patchChildren https://localhost/jse/AppScript:1605:7
	patch https://localhost/jse/AppScript:1480:7
	patchChildren https://localhost/jse/AppScript:1605:7
	patch https://localhost/jse/AppScript:1480:7
	patchChildren https://localhost/jse/AppScript:1605:7
	patch https://localhost/jse/AppScript:1480:7
	patchChildren https://localhost/jse/AppScript:1605:7
	patch https://localhost/jse/AppScript:1480:7
	patchChildren https://localhost/jse/AppScript:1605:7
	patch https://localhost/jse/AppScript:1480:7
	patchChildren https://localhost/jse/AppScript:1605:7
	patch https://localhost/jse/AppScript:1480:7
	patchChildren https://localhost/jse/AppScript:1605:7
	patch https://localhost/jse/AppScript:1480:7
	redrawSync https://localhost/jse/AppScript:1916:8
	updateSync https://localhost/jse/AppScript:1942:10
	patchChildren https://localhost/jse/AppScript:1612:7
	patch https://localhost/jse/AppScript:1480:7
	redrawSync https://localhost/jse/AppScript:1916:8
	redraw https://localhost/jse/AppScript:1755:8
	redraw/vm._redrawAsync< https://localhost/jse/AppScript:1757:73
	call https://localhost/jse/AppScript:293:4
`````

**Comment by leeoniya** [comment]
could you narrow down the first non-working domvm commit or provide a repro?

i can't think of anything recent that would affect this part of the code. in app-space there shouldnt be anything that can trip this aside from touching the dom manually.

**Comment by lawrence-dol** [comment]
So far I have narrowed it down to when I create a text-area with a value, but cannot reproduce the behavior in a fiddle. However, [the fiddle](https://jsfiddle.net/LawrenceDol/5ytm7pkf/) *does* show one unexpected thing -- redraws always occur in pairs; that is, DOMVM seems to invoke my view render function twice for every redraw. This is unrelated but might want to be looked into.

**Comment by leeoniya** [comment]
you're incrementing `redraw` twice in `render()`, so it looks like it redraws twice.

here's a single increment: https://jsfiddle.net/5ytm7pkf/99/

**Comment by lawrence-dol** [comment]
Oh, crap. We need a face-palm icon in Git Hub.

**Comment by lawrence-dol** [comment]
@leeoniya 

I have [pinned it down in this fiddle](https://jsfiddle.net/LawrenceDol/5ytm7pkf/). 

It happens when:

  1. A value is given for a text area as a simple child (not an array), and
  2. The value is a function, with a toString(), and
  3. The return value of `toString()` is an empty string, and then
  4. The view is redrawn.

Very odd.

**Comment by lawrence-dol** [comment]
Thanks for the evaluation @leeoniya. I agree that no change should be made in DOMVM. though it would be nice if an inexpensive protection could be added. I've been bitten by passing an object in this way before -- I have a wrapper function that performs some additional checks in developer mode, one to ensure that `attributes` is an object, and the other to ensure that `children` is not an object unless it's an array. So I've added a third to ensure that `children` is not a function.

Note that in this case the use is retrospectively a clear mistake due to my very early misapprehension that I needed to supply the function in order to get it's live value during render. At the time I still hadn't twigged that the vDOM is rebuilt for every render. It may be a practice carried over from my Mithril code. Certainly that's where I picked up the use of property getter/setter functions.

This `toString` implementation was a bit of an accident/experiment. I was adding the `toJSON()` function for serialization when it occurred to me that the string representation of this function could logically be considered the string of its value. I'll give it some thought, but there's a good argument that `toString` should be either dropped, or throw an exception -- I lean toward the latter, since I don't really like using `xxx` instead of `xxx()` to read a get/set value anyway; it could be considered an antipattern, though it has utility in converting data models to strings for debugging.

**Comment by leeoniya** [comment]
> though it would be nice if an inexpensive protection could be added

i'll definitely bench this and maybe it'll make it in. it may turn out that having more type uniformity for `body` would be a net win.

> I have a wrapper function that performs some additional checks in developer mode, one to ensure that attributes is an object, and the other to ensure that children is not an object unless it's an array. So I've added a third to ensure that children is not a function.

i'll add these checks to the devmode build of domvm. TypeScript is starting to look pretty good for this kind of stuff ;)

**Comment by lawrence-dol** [comment]
> please test it out in your app before i cut a new release.

It works just fine. I measure a 6% performance *improvement* in Firefox.

`````
/* File 7: domvm.micro.min.js */
// https://github.com/domvm/domvm (3.x-dev, micro build)
!function(e,n){"object"==typeof exports&&"undefined"!=typeof module?n(...
`````
