### ISSUE TITLE
For values returned from diff(), null === {}

### ISSUE THREAD

**Issue by jlgrall** [domvm/domvm#204]
The code responsible for this is in [`vm.diff.cmp`](https://github.com/domvm/domvm/blob/3.4.6/src/view/ViewModel.js#L73). And it is executed during [`redrawSync()`](https://github.com/domvm/domvm/blob/3.4.6/src/view/ViewModel.js#L252).

Small test:

```javascript
// Dummy vm for testing:
var vm = domvm.createView({render: function() {}});
vm.config({diff: function() {return 0;}});

// The comparison function that compares successive values returned by diff()
// doesn't differentiate between null and {}:
console.log("null === {}:", vm.diff.cmp(vm, null, {}));      // => false
console.log("null === null:", vm.diff.cmp(vm, null, null));  // => false

// It is actually the same problem for any primitive value:
console.log("12 === 34:", vm.diff.cmp(vm, 12, 34));    // => false
console.log("12 === 12:", vm.diff.cmp(vm, 12, 12));    // => false
```

**Comment by leeoniya** [comment]
so...`diff()` was originally designed for handling just arrays and objects; the simplistic handling for primitives was added later by just the simple `===` test.

there's a caveat for this in the docs [1], but yeah the situation can be improved.

probably adding `if (o == null || isVal(o)) return o != n;` to `cmp()` would not have much perf impact.

[1] https://github.com/domvm/domvm#view-change-assessment

**Comment by jlgrall** [comment]
I was thinking about something like this which would have less impact than your solution while accepting more kinds of primitives:
```javascript
function retFalse() { return false; }

var cmpFn = isArr(o) ? cmpArr :  // array
            (typeof o === "object") ?  (o === null ? cmpObj : retFalse) :  // object or null
            retFalse;  // primitive
return !(o === n || cmpFn(o, n));
```

**Comment by leeoniya** [comment]
how about this:

```js
function cmp(o, n) {
  return !(o === n || (isArr(o) ? cmpArr(o, n) : isPlainObj(o) ? cmpObj(o, n) : false));
}
```

https://jsfiddle.net/6w73tm4q/

**Comment by jlgrall** [comment]
It is much better, especially for automatic inlining.

Just one thing. Do you really want to exclude all objects that are not plain from going through ` cmpObj(o, n)` ?  I think that it could be a good idea, but I am not sure. At least, this introduces a potentially breaking change from the current behavior.

**Comment by leeoniya** [comment]
> Do you really want to exclude all objects that are not plain

kinda. for example, things like `new Date` and `new Promise` dont produce objects that are easily discernable without explicit checks, yet dont make sense to pass through cmpObj. also, cmpObj would iterate an instance's public methods, etc.

worst case for this "breaking" change is a perf regression, so i'm not too concerned.

**Comment by leeoniya** [comment]
pushed the changes. let me know if that works as you expect.

thanks for reporting, btw. it's been one of those micro-warts.

**Comment by leeoniya** [comment]
> Why the double negative with the function vm.diff.cmp() (when the result is returned and then when it is used in redrawSync()) ?

cause semantically naming things is hard while trying to keep the names terse. in isolation, a generic util function called `cmp*` feels like it should return `true` if same and `false` if different (imo). while a function designed to mimic sCU semantics should return `false` if same and `true` if different. the whole thing goes off the rails again cause`diff` is equally ambiguous and isnt helped by the fact that it doesnt return a boolean or delta in the public-facing interface. i'm open to improvements in renaming the private functions and reducing some of the negation twiddling. i agree that it's a bit awkward to follow, especially in a shortened conditional chain.

> Why do you create a new function vm.diff.cmp() for every vm when you could create it just once and assign it multiple times ?

if you're referring to this [ViewModel.js#L73-L75](https://github.com/domvm/domvm/blob/master/src/view/ViewModel.js#L73-L75), then it looks like an oversight :)

**Comment by jlgrall** [comment]
Ok, I see. You are trying to name many things with only a limited number of short names :)

But it it still is very different from a sCU in my opinion. To use a sCU semantic, a user would do:
```javascript
vm.config({diff: function() {}});
vm.diff.cmp = function(vm) {
  // Compute and return sCU result...
};
```
Which is already so different that it would cast aside any expectation of keeping the sCU semantic (on the contrary, from reading only this code, you would expect to return true if same). I think that someone who would write that would already have read enough of domvm's source code that there would be no need to pretend to keep the sCU semantic.

> if you're referring to this [ViewModel.js#L73-L75](https://github.com/domvm/domvm/blob/master/src/view/ViewModel.js#L73-L75), then it looks like an oversight :)

Yep :)

**Comment by leeoniya** [comment]
> But it it still is very different from a sCU in my opinion. To use a sCU semantic, a user would do:

well, that's not really the intended api. the design is:

```js
vm.config({
  diff: {
    val: function(vm, data, key, parent, idx) {
      // return some value to cache for diffing in cmp
    },
    cmp: function(vm, oldVal, newVal) {
      // like sCU, return false to prevent re-render
    }
  }
});
```

unlike the internal util `cmp*`, this `cmp` returns false if same (oldVal eq newVal), to mimic sCU. i don't really expect people to be reading internals to understand how it works; the docs should be sufficient.

if the user supplies a a function for `diff`, then it becomes `val` and `cmp` defaults to the internal impl that special-cases array and object val returns. else if the user supplies an object for diff, then it's possible to DIY the whole thing and not deal with domvm's default cmp.

> So, equ* or eq* would be a better choice. My2c.

that sounds like a good idea. i guess since the docs were never really updated to show the extra `{val, cmp}` diff signature, we can technically change it to `{val, eq}` without breaking any contracts. by calling it eq and moving away from sCU, we can remove a couple inversions, too.

**Comment by jlgrall** [comment]
> else if the user supplies an object for diff, then it's possible to DIY the whole thing and not deal with domvm's default cmp.

Oh, I missed that. So yeah the user doesn't need to look at the internals.

`{val, eq}` seems good.

**Comment by leeoniya** [comment]
changes are in. definitely an improvement in clarity.

dunno if i should add the diff object signature to the docs, now that there are less footguns. the object signature allows you to avoid an array allocation if you want to diff an immutable `data` object or array, but it's such a tiny win in 99.5% of real-world cases that i'm not sure if polluting the docs is worth it.

**Comment by jlgrall** [comment]
Just an idea:
```javascript
// These 2 would work as currently:
vm.config({diff: {val: fn() {...}}});
vm.config({diff: {val: fn() {...}, eq: fn() {...}}});

// This would internally use a strictEq() function:
vm.config({diff: {val: fn() {...}, strict: true}});

// With the strict eq function:
function strictEq(vm, oldVal, newVal) {
  return oldVal === newVal;
}
```
You wouldn't even need to publicly document the `diff: {val, eq}` option. You could only document the `diff: fn` and the `diff: {val, strict}` options. That would be enough.

**Comment by leeoniya** [comment]
nah. if someone *really* needs to micro-optimize, i'd rather just add the `diff: {val, eq}` signature to the Optimizations [1] section.

https://github.com/domvm/domvm#optimizations

**Comment by jlgrall** [comment]
Well there is still a problem with [eq()](https://github.com/domvm/domvm/blob/master/src/utils.js#L94). For example:
```javascript
eq({}, null);  // => true
eq({}, 1);  // => true
```

This may happen because if one time you compare the old value `null` and the new value `{}`, the next time `{}` will be your old value, so the situation might be reversed.

Here is a possible solution:
```javascript
function eq2(o, n) {
    return o === n || (
        typeof o === typeof n && n !== null && (
            isArr(o) ? eqArr(o, n) :
            isPlainObj(o) ? eqObj(o, n) :
            false
        )
    );
}
```
The idea is that if `o` and `n` are not the same type, we return `false`. We need to take care of the special case where either `o` or `n` is `null`. But we can actually skip the `o !== null` because that will fallthrough the following tests and return `false`.

**Comment by leeoniya** [comment]
@jlgrall even this solution still has edge cases since `eqArr` and `eqObj` assume they're passed identically typed args, but eq2 provides no such guarantees. for example `eq2({0: 0, 1: 1}, [0,1]) === true`.

the only foolproof solution is special-casing `null` and always testing both sides before passing them to `eqArr` or `eqObj`. however, i think the latter can only occur synthetically and rarely in actual app code. my [perhaps controversial] option is that handling `eq({}, null);` and any `null` and `undefined` is a reasonable expectation whereas `eq({}, 1);` would rarely actually happen. most type confusion that occurs in app space is typically loose and on plain values. `"1"` vs `1`, `""` vs `undefined`. i cannot think of a situation where you could pass both an object and a plain value for diffing - this would mean you're doing the same weird type-checks all over the rest of your app code.

so we can either:

1. agree that eq expects same-type objects/arrays, null, undefined, or any plain values. this covers all sane cases, IMO. we can also add some more expensive typechecking to DEVMODE builds and alert if this assumption is violated.
```js
function eq3(o, n) {
  return (
    o === n ? true :                    // eqv
    o == null || n == null ? false :    // null & undefined
    isArr(o) ? eqArr(o, n) :            // assumes n is also Array
    isPlainObj(o) ? eqObj(o, n) :       // assumes n is also Object (repeats 1 null check)
    false
  );
}
```

2. take the perf hit of always testing both sides.

```js
function eq3(o, n) {
  return (
    o === n                        ? true :          // eqv
    o == null || n == null         ? false :         // null & undefined
    isArr(o)      && isArr(n)      ? eqArr(o, n) :   // two arrays
    isPlainObj(o) && isPlainObj(n) ? eqObj(o, n) :   // two objects (repeats 2 null checks)
    false
  );
}
```

personally i prefer <span>#</span>1. because i prefer the perf of a cheaper and more common `!=` check of matched types than accommodating what IMO are unrealistic real-life situations.

**Comment by leeoniya** [comment]
for now, i pushed the <span>#</span>1 variant since it solves the obvious issues with `eq({}, null)`.

**Comment by lawrence-dol** [comment]
I agree with using #1.

**Comment by jlgrall** [comment]
@leeoniya I hadn't seen that case. Good catch. But I think that you can simplify further.

In your #1, the `o == null` is not needed: if `o` is `null`, it will fallthrough the following tests and return `false`. So you are left with:
function eq3(o, n) {
  return (
    o === n ? true :                    // eqv
    n == null ? false :                 // null & undefined
    isArr(o) ? eqArr(o, n) :            // assumes n is also Array
    isPlainObj(o) ? eqObj(o, n) :       // assumes n is also Object (repeats 1 null check)
    false
  );
}

In your #2, the `o == null || n == null         ? false :` line can be removed: it doesn't change the result. So you are left with:
```javascript
function eq3(o, n) {
  return (
    o === n                        ? true :          // eqv
    isArr(o)      && isArr(n)      ? eqArr(o, n) :   // two arrays
    isPlainObj(o) && isPlainObj(n) ? eqObj(o, n) :   // two objects (repeats 2 null checks)
    false
  );
}
```

I prefer the #2 because it leads to less surprising behaviors. But I understand that domvm wants to be fast, and that the handled cases can be reduced to _reasonable expectations_. (Though I have no idea if Array.isArray()`is really much slower than `== null` after JIT compilation. I only know that `=== null` has the same speed as `typeof`, so probably `isArray()` is fast too.)

**Comment by leeoniya** [comment]
> In your <span>#</span>1, the `o == null` is not needed: if `o` is `null`, it will fallthrough the following tests and return `false`. 

that's technically true, but i'd rather return as early as possible if `o == null && n != null`, otherwise we end up with an extra `isArray(o)` and `isPlainObj(o)`. for the other cases, you only incur an extra cheap null check.

if you want stricter handling, there's always `{val, eq}` ;)

thanks for the feedback.

**Comment by jlgrall** [comment]
Ok. Last question. About the `vm.config()` function.

How should we set the `diff` and the `eq` functions ?
1. `vm.diff = {val: myDiffFn, eq: myEqFn}`
2. `vm.config({diff: {val: myDiffFn, eq: myEqFn}}`

Why is the second possibility only allowed in [vm.config()](https://github.com/domvm/domvm/blob/master/src/view/ViewModel.js#L73) when `FEAT_DIFF_CMP` is off ?

**Comment by leeoniya** [comment]
`FEAT_DIFF_CMP` is only disabled in the minimal `pico` build [1], which removes some helpful features [2] to shave byte size and speed up some internals but requires more stuff to be explicit. this includes the function signature for diff, but leaves the raw `{val, eq}` sig in place. this allows Rollup to dead-code-elim the internal `eqArr`, `eqObj` and `eq`, plus the implicit diff setup.

[1] https://github.com/domvm/domvm/blob/master/build.js#L45
[2] https://github.com/domvm/domvm/tree/master/dist

**Comment by jlgrall** [comment]
So in pico, I can do `vm.config({diff: {val: myDiffFn, eq: myEqFn}}` and it will work. But in nano, it won't work ? That seems strange.

**Comment by leeoniya** [comment]
besides for `FLUENT_API`, the builds extend each other. nano includes everything that pico does, etc.

**Comment by jlgrall** [comment]
You have a bug, see the edit to my previous comment.

**Comment by leeoniya** [comment]
ah, your're right! it needs another copy of the else branch in there 😕, or s slight control-flow tweaking to avoid copy-pasta.

on it!

**Comment by leeoniya** [comment]
https://github.com/domvm/domvm/commit/a93e55bee0db3c683b7c52e4e50edb38f307ddfd#diff-623c25c223969bc3a1e61ad61cb93341
