### ISSUE TITLE
[domvm-mobx] MobX bindings for domvm

### ISSUE THREAD

**Issue by jlgrall** [domvm/domvm#205]
Hi, I made a simple script that allows me to use MobX with domvm:

https://github.com/jlgrall/domvm-mobx

(Just posting this here so that it can be found. Feel free to close this.)

Note: there is not yet a release as I am still experimenting with it. I think I finally found a good API which allows users to just use the `observer()` and it will work even if they use some of domvm's advanced tricks. The only problem that I could not completely resolve is the mandatory keying of sub-views in dynamic lists. It is the only thing that the user needs to be aware of when using domvm-mobx.

**Comment by leeoniya** [comment]
that's pretty neat! i'm not too familiar with mobx, but i'll definitely take a look when i get a chance.

if you haven't seen yet, i have some demos with deeply-immutable structures using Freezer [1]: https://domvm.github.io/domvm/demos/playground/#immutable and some reactive views using Flyd [2] streams (which seems more similar to the mobx observable approach): https://domvm.github.io/domvm/demos/playground/#streams

i wonder if the stream adapter can be made more generic to also handle observables? or if mobx's interfaces can be exposed as streams to make use of the existing adapter interface.

[1] https://github.com/arqex/freezer
[2] https://github.com/paldepind/flyd

**Comment by jlgrall** [comment]
Yep MobX is huge. It is not for every project. But I thought it was weird that you listed MobX in your doc as a complementary library whereas there was no easy way to really integrate it with domvm.

My first idea was to hook into the domvm stream API. But it couldn't work because streams are produced by the render() methods. So they cannot handle the render() method itself, which is what is needed for MobX to track which observables are accessed.

Here is how MobX reactions work in a nutshell:
- Each reaction instance keeps track of which observable it currently observes. The tracking is done with `reaction.track(fn)`: this executes fn while registering which observables are being accessed during its execution. Afterwards, if any of the observables changes, then the reaction is notified. So for domvm, we need to create a reaction for every live vm, and the tracked function will always be the render() method. When the reaction is notified, we schedule a redraw of the vm. Finally, it is important to destroy the reaction when not needed so that its resources can be reclaimed.
- Observables are not values, they are always properties (except for boxed observables). Properties are defined with getters: the getter notifies MobX that it is being accessed before returning its value. MobX can then match the accessed observables with the running observers.

**Comment by leeoniya** [comment]
would you be interested in moving your domvm-mobx repo into the domvm org? it'd probably require providing an MIT license, too (for uniformity). some basic tests can be added also.

**Comment by jlgrall** [comment]
Yep, we can do that (and it is already MIT licensed). I have never done that, so tell me if you need anything, or what changes would be needed.

Here is what I am planning for the future:
I am still experimenting with it, and will use it in one of my projects within the next month or so. So I will be able to see if it works well.

Then, I will continue to maintain it if MobX or domvm introduces any change that breaks it.

About testing, I haven't put any thought in that yet. Currently I am just manually running the examples from the Readme.md, to make sure they work. But we can probably use the same testing framework that domvm uses.

About mobx-state-tree: it should work out of the box, but if there is any issue, I can look into it. I like that it allows to write the code in a very declarative way: you get your data and the computed values in a nicely organized tree. Very little boilerplate in the code, easy to read. Also easy to use: the state is always coherent and it is like using normal javascript values and objects.
Unfortunately, it is even bigger than MobX (and you have to include it in addition to MobX), so I would only use it in complex single page apps or things like that.

**Comment by leeoniya** [comment]
@jlgrall i sent you an invite to the domvm org, you can read more about repository transfer here:

https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account/
