### ISSUE TITLE
Error: unnecessarily redrawing child vm when parent vm is also redrawing

### ISSUE THREAD

**Issue by jlgrall** [domvm/domvm#206]
Test case: https://gist.github.com/jlgrall/674704d98b7223f9a87264171b5f5921

Problem:  
Once we schedule an async redraw (with a `vm.redraw()`), the redrawing will occur even if the vm is removed in between, and even if a parent of the vm is also scheduled for redrawing (either before or after the child). This may cause unexpected errors and unnecessary renderings.

**Comment by leeoniya** [comment]
there are a couple things going on here. you technically should not be pulling the vms from the live dom for the purposes of redrawing. i assume this is just for the repro and not used in actual code? pulling state from globals is also not great.

> even if a parent of the vm is also scheduled for redrawing

the async nature of redraw if simply a side-effect of the rAF-based debounce [1], which is done per-vm. there is no redraw scheduler or queue of any kind. the vms do not (and cannot) check whether their parents are scheduled for redraw, because, again, there is no explicit queue.

for child-after-parent redraw calls could be a simple matter of walking up the vtree and checking all ancestor flags, but first we 'd have to rework how redraw operates. it could be worthwhile, as long as perf is unaffected. the parent-after-child would be more expensive since every vm would need to walk its entire sub-tree to cancel all queued redraws (and there has to be a way to actually cancel them).

> the redrawing will occur even if the vm is removed in between

an unmounted vm, should be redrawable without errors. it's possible that we can tweak `isMounted` [2] to not redraw at all.

[1] https://github.com/domvm/domvm/blob/master/src/utils.js#L107
[2] https://github.com/domvm/domvm/blob/master/src/view/ViewModel.js#L234

**Comment by jlgrall** [comment]
Yeah, there are different things going on here. I will try to address them separately.

I actually met this problem with my [domvm-mobx bindings project](https://github.com/jlgrall/domvm-mobx). Because vm are redrawn by reactions, it can come in any order. Also, any vm that has its data changed will receive a `vm.redraw()`, even if it has been removed. So this causes problems in potentially unexpected ways.

After thinking about it for a while, I decided to make this issue with a simpler test case that shows the problem without including the complexity of domvm-mobx. That would also allow me to get some feedback, even if ultimately I only need this resolved for domvm-mobx.

## Comments on your answer:

- You said: "you technically should not be pulling the vms from the live dom for the purposes of redrawing". I do this in actual code. How do you do it when you want to only redraw some sub-views ?
- Passing the number object directly instead of the array and index to the child doesn't fix the problem:
  - with domvm-mobx, we want to dereference values as late as possible, so when there is a list we almost always pass the list and the key to the children. This comes from the fact that [it is the property access that is observable, not the value](https://github.com/domvm/domvm/issues/205#issuecomment-443187539).
  - in other projects, I would actually pass the object like you do. But even in this case, the redraw still executes with an object that was removed from the application state and which might be in an inconsistent state or whose manipulation might cause errors, even though the render result will only show in the dom for a short time before the parent is re-rendered and the child vm is removed.
- It seems to me that domvm actually requires that a vm
well the first render is executed before 
- You said: "An unmounted vm, should be redrawable without errors". Well, mounting a vm requires that domvm knows what to mount, thus [the first render always happens before the vm is mounted](https://github.com/domvm/domvm/blob/master/src/view/ViewModel.js#L183), which means that in this case, an unmounted vm must be renderable without errors. I think the difference is that during the first render the user expects the `render()` to be executed (obviously), whereas when the user removes an element from the list and asks the list to be redrawn, he expects that from this point on, the vm to be removed won't be redrawn. Unfortunately in complex apps, another part might independently ask that child vm to be redrawn, causing unexpected errors. And in domvm-mobx, this is exactly what happens: any observer vm that has modified observed data is redrawn.

## The problems:

I see 2 problems:
- a child vm is rendered twice if its parent is also being redrawn. 2 cases: the child being scheduled before or after the parent.
- a child vm is re-rendered even if the parent removes and unmounts the child vm. This happens even if the parent is actually rendered before the child. Note: it would also be great to prevent this when both the child and the parent are scheduled for redrawing, wether the child is scheduled before or after the parent.

## A solution

This is a simple solution that I could easily integrate into domvm-mobx.  
The idea would be to replace [`vm.redraw()`](https://github.com/domvm/domvm/blob/master/src/view/ViewModel.js#L111) with a different function and to declare a new `doRedraws()` function.

The `vm.redraw()` function would:
- store the vm scheduled for redrawing into a Set.
- schedule the execution of the `doRedraws()` function (with a `requestAnimationFrame()`) if it is not already scheduled.

The `doRedraws()` function would:
- loop the vms inside the Set:
  - only redraw the vm if none of its parents is already in the Set.
- empty the Set.

Note: I would probably throw an error if a `vm.redraw()` is called during a `doRedraws()`.

This would be less overhead than the current implementation of [`ViewModel.prototype.redraw()`](https://github.com/domvm/domvm/blob/master/src/view/ViewModel.js#L111) and [`raft()`](https://github.com/domvm/domvm/blob/master/src/utils.js#L107): we create only a Set and a reference for each stored vm. Calling `vm.redraw()` multiple times is not a problem and is quick. The whole processing would be in the `doRedraws()`, but checking the parents would make no difference in the common case of `vm.root().redraw()`, and very little overhead otherwise, while allowing to skip unneeded rendering when children and parents vm are scheduled together.

Browser compatibility: the [Set](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set) is part of the ES6 specification, but it was already available in some browsers that were not ES6 compliant, like IE11. For older browsers, I could add an integer `id` property to the vm and store the scheduled vms in a plain object instead of a Set.

This solution fixes all the problems I identified previously and is easy to implement. The only remaining possible problem would be when an unmounted child is scheduled for redrawing but its parent is not. I think that this cannot happen with domvm-mobx because when the vm is unmounted, its Reaction is destroyed, preventing any further scheduling of redrawing. (So this is just a side effect of the user not needing to schedule the redrawings himself.)

Note: I did not check how other libraries are managing their async redrawing, so there might be other or better solutions.

**Comment by leeoniya** [comment]
here's the userland impl roughly as you outlined, it works quite well. you'll also see how i grab the descendant vms, without querying the DOM (just walk the vtree).

> For older browsers, I could add an integer id property to the vm and store the scheduled vms in a plain object instead of a Set.

there are es5 shims for `Map` and `Set` [1], so i wouldn't pollute this impl with any special handling.

[1] https://github.com/paulmillr/es6-shim

impl:

```js
var redrawQueue = new Set();

function drainQueue() {
  redrawQueue.forEach(vm => vm.redraw(true));
  redrawQueue.clear();
}

// gets all descendent vms
function getVmsBelow(node, acc) {
  if (acc == null)
    acc = [];
  else if (node.vm != null)
    acc.push(node.vm);

  if (Array.isArray(node.body))
    node.body.forEach(node => getVmsBelow(node, acc));

  return acc;
}

// gets all ancestor vms
function getVmsAbove(node, acc) {
  if (acc == null)
    acc = [];
  else if (node.vm != null)
    acc.push(node.vm);

  if (node.parent != null)
    getVmsAbove(node.parent, acc);

  return acc;
}

domvm.ViewModel.prototype.redraw2 = function() {
  // 1. bail if self or an ancestor is in queue
  if (redrawQueue.has(this) || getVmsAbove(this.node).some(vm => redrawQueue.has(vm)))
    return;

  // 2. remove any descendents from queue
  getVmsBelow(this.node).forEach(vm => redrawQueue.delete(vm));

  // 3. add self to queue
  redrawQueue.add(this);

  requestAnimationFrame(drainQueue);
}
```

demo:

```js
const el = domvm.defineElement;
const vw = domvm.defineView;
const cv = domvm.createView;

function ListView() {
  return (vm, items) => {
    console.log("ListView render");

    return el("ul", items.map(item =>
      vw(ItemView, item)
    ))
  }
}

function ItemView() {
  return (vm, item) => {
    console.log("ItemView " + item + " render");

    return el("li", item)
  }
}

const items = "abc".split("");

var listVm = cv(ListView, items);

listVm.mount(document.body);

// instead of querying the DOM
var subVms = getVmsBelow(listVm.node);

setTimeout(() => {
  listVm.redraw2();
  // will not double-queue, since already queued
  listVm.redraw2();
}, 1000);

setTimeout(() => {
  listVm.redraw2();
  // will not double-queue, since ancest is queued
  subVms.forEach(vm => vm.redraw2());
}, 2000);

setTimeout(() => {
  subVms.forEach(vm => vm.redraw2());
  // will not double-queue, since adding ancest after descendants will clear them
  listVm.redraw2();
}, 3000);
```

**Comment by leeoniya** [comment]
as it turns out, IE11 does in fact have a `Set` implementation that's compliant-enough [1] for this to work without any additional code. this means we can consider replacing the main async redraw impl as long as there's no significant perf impact on typical cases.

cc @lawrence-dol thoughts?

[1] https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set#Browser_compatibility

**Comment by jlgrall** [comment]
What I had in mind was actually much simpler. Just drop this code after domvm is loaded, it should work out of the box:

```javascript
var redrawQueue = new Set();
var redrawQueueRAF = 0;

function drainQueue() {
    for (var vm of redrawQueue) {
        var node = vm.node;
        
        if (node == null) continue; // vm was unmounted
        
        while(node.parent != null) {
            node = node.parent;
            if (node.vm != null && redrawQueue.has(node.vm))
                break;
        }
        
        vm.redraw(true);
    }
    
    redrawQueue.clear();
    redrawQueueRAF = 0;
}

var originalRedraw = domvm.ViewModel.prototype.redraw;
domvm.ViewModel.prototype.redraw = function(sync) {
    if (sync) return originalRedraw.call(this, sync);
    
    redrawQueue.add(this);
    
    if (redrawQueueRAF === 0) redrawQueueRAF = requestAnimationFrame(drainQueue);
    
    return this;
}
```

Note: for IE, we would need to replace `for..of` with something like:
```javascript
var vms = redrawQueue.values();
for (var i = 0; i < vms.length; i++) {
    var vm = vms[i];
    ...
}
```

**Comment by leeoniya** [comment]
that looks pretty good!

IE11 doesnt support `Set.values()`, so we'd either need to use `.forEach()` to grab them or probably just use `.forEach()` in a single impl.

**Comment by jlgrall** [comment]
> IE11 doesnt support `Set.values()`

Good catch. Yep `.forEach()` would be the way to go then. It would work on all modern browsers and IE11+. Older browsers would use an ES6 shim which supports `.forEach()`, as you said earlier.

The best solution would be to test for availability of the `for..of` and use it, because it is faster. And fallback to `.forEach()` otherwise. Unfortunately, I think it is not feasible because writing a `for..of` in the code would prevent parsing of the rest of the script in incompatible browsers, even if they wouldn't execute it.

But I cannot test with IE, so I don't know.

**Comment by leeoniya** [comment]
here's my iteration of it with `Set.forEach` and utilizing `vm.parent()` (which gets the parent vm):

```js
var redrawQueue = new Set();
var redrawQueueRAF = 0;

function drainQueue() {
  redrawQueue.forEach(vm => {
    // don't redraw if vm was unmounted
    if (vm.node == null)
      return;

    // don't redraw if an ancestor is also enqueued
    var parVm;
    while (parVm = vm.parent()) {
      if (redrawQueue.has(vm))
        return;
    }

    vm.redraw(true);
  });

  redrawQueue.clear();
  redrawQueueRAF = 0;
}

var originalRedraw = domvm.ViewModel.prototype.redraw;

domvm.ViewModel.prototype.redraw = function(sync) {
  if (sync)
    return originalRedraw.call(this, sync);

  redrawQueue.add(this);

  if (redrawQueueRAF === 0)
    redrawQueueRAF = requestAnimationFrame(drainQueue);

  return this;
}
```

> Edit: note that the line if (node == null) continue; // vm was unmounted resolves the problem of an unmounted child scheduled for redraw when its parent is not scheduled

yep makes sense in this case when you're not proactively preventing child vms from ever being enqueued (or proactively removing them when their parent is enqueued) as i was doing. in your impl you could redraw the parent that unmounts child vms which are also queued afterwards, so they need to be skipped. your way is cheaper so 👍.

**Comment by jlgrall** [comment]
Looks good to me.

**Comment by jlgrall** [comment]
Wait, actually it doesn't work ! If I replace my version with yours, the first render is ok, but then no redraw is actually performed.

**Comment by jlgrall** [comment]
Quick fix for your code, in `drainQueue()`:
```javascript
    var parVm = vm;
    while (parVm = parVm.parent()) {
      if (redrawQueue.has(parVm))
        return;
    }
```

**Comment by leeoniya** [comment]
ah, good catch.

**Comment by lawrence-dol** [comment]
I have no objections in principle. I've not yet had a need for granular redraws, but I can readily see how I could utilize them; thus automatically avoiding redundant redraws is a good thing, especially if it has no impact on the simple redraw cases.

**Comment by leeoniya** [comment]
i've integrated this into the core, so give it a whirl

**Comment by leeoniya** [comment]
v3.4.7 is out with these changes. thanks!

**Comment by jlgrall** [comment]
Tested v3.4.7: it works :)

**Comment by jlgrall** [comment]
@leeoniya Don't forget to add requirement for a` Set` shim in readme.md and in the v3.4.7 release notes.

**Comment by leeoniya** [comment]
I updated readme to say down to IE11 rather down to IE9. IE11 has enoigh Set support to work without shims.
