### ISSUE TITLE
Event doesn't fire on children when using .innerHTML and parameterized listeners

### ISSUE THREAD

**Issue by Veid** [domvm/domvm#210]
Hey,

https://jsfiddle.net/45rfm9tx/1/

Try to click the bold word and notice that the event doesn't fire. Am I missing something about parameterized event listeners or is this a bug?

P.S.
domvm is fantastic and I love it very much!

**Comment by leeoniya** [comment]
hey @Veid ,

it's probably because the event phase emulation for parameterized listeners is not fully implemented.

it's not a bug per se, since i knew going into the event system rewrite that the impl would not be fully conformant :/

honestly, i'm not sure it's worth the trouble, since it would add a bunch of code (i think), and it's pretty easy to work around. case in point: your example works as expected with a non-parameterized listener and if you need the vnode it fired from, you can read off `e.target._node` (or the closest ancestor that has a `_node` property).

if you'd like to contribute some improvements that dont impact size or perf too much, the current handler code is fairly easy to understand: https://github.com/domvm/domvm/blob/master/src/view/patchEvent.js#L58-L74

**Comment by Veid** [comment]
Thanks for the reply,

I thought as much, because I did notice that the non-parameterized listener worked just fine. I think I trust you when you say it may not be worth it. I've not spent a lot of time with the internals of domvm, but I would assume the '.innerHTML' bits are going through as a text node. So we'd need some code that looks for html in the text node and applies the handler code to them as well.

As an aside, is there a better way to deal with displaying chunks of html in this way? Wanting to render a piece of markdown, for example. Reading through the docs, the whole '.innerHTML' thing seems like it's discouraged / odd?

**Comment by leeoniya** [comment]
> but I would assume the '.innerHTML' bits are going through as a text node. So we'd need some code that looks for html in the text node and applies the handler code to them as well.

well, no. it goes through a DOM property, exactly as you'd do in plain js [1]. once it's appended into the DOM, events should work as they normally do.

looking at it a bit closer, your example is almost certainly hitting this early exit when it does not detect a domvm node attached to the event target element (created by innerHTML):

https://github.com/domvm/domvm/blob/master/src/view/patchEvent.js#L61-L62

domvm used to climb up the DOM from e.target to the nearest domvm-created element (w/._node) and use that to trigger the handler. but this was causing issues described in the [commit that changed this behavior](https://github.com/domvm/domvm/commit/02d493876d12ec9ea9d7d717ef9340a4d0b61c88). unfortunately i don't have the code on hand that demonstrates the bug(s) this fixed (i'll have to dig around for it).

> As an aside, is there a better way to deal with displaying chunks of html in this way? Wanting to render a piece of markdown, for example. Reading through the docs, the whole '.innerHTML' thing seems like it's discouraged / odd?

nothing wrong with innerHTML besides what's mentioned in the readme [2]. there's not really another way to render markdown in a container in the DOM/JS (that's the way i do it, too). innerHTML is diff'd like any other attribute/property but tends to be a big string, so there's that performance consideration, but i wouldn't worry about it too prematurely. if the innerHTML is static, you can always append to a domvm-created element in a willInsert or willMount hook so it doesnt get diffed on every redraw.

[1] https://developer.mozilla.org/en-US/docs/Web/API/Element/innerHTML
[2] https://github.com/domvm/domvm#innerhtml

**Comment by lawrence-dol** [comment]
Should this issue be closed? Is the resolution/response that parameterized handlers don't see events from inner-HTML subnodes?

**Comment by leeoniya** [comment]
agreed, this is not likely to change.
