### ISSUE TITLE
Changing a textarea value.

### ISSUE THREAD

**Issue by lawrence-dol** [domvm/domvm#212]
I have the requirement to truncate an input/textarea at the current cursor position when a specific key is pressed. So I implemented code in the key handler to get the associated data model and change it's value (which triggers redraw via a change handler):

```js
let elm=evt.target, val=elm.value, csr=elm.selectionStart;
let mdl=elm._node && elm._node.data && elm._node.data.model;
if(mdl && val && csr<val.length) {
    mdl.value(val.substring(0,csr));
    mdl.keyed(true);
    }
```

This works consistently on input fields, but with textareas it works for the initial value, but not after I've typed a value into the field. After experimenting with other options, I added an onchange handler to the fields (previously only had an oninput handler) and tried updating the element's value, like this:

```js
let elm=evt.target, val=elm.value, csr=elm.selectionStart;
if(csr<val.length) {
    elm.value=val.substring(0,csr);
    elm.dispatchEvent(new Event("change"));
    }
```

Which works, apparently consistently, for both types of field because the change event handler updates the model. It also happens to be simpler. But I expect to be able to entirely drive the view by updating the model, trigger a repaint, and have everything redrawn with the current model values.

So I wanted to double check whether updating the backing model should've worked just fine (and that implies that I have a problem with DOVVM identifying that the input field value has changed).

I feel like this must be related to the difference between the input's value attribute, and textarea's value content. Am I missing anything obvious?

**Comment by leeoniya** [comment]
there shouldn't be any difference between text input and textarea. the code that determines whether an attr should be compared to the dom or to the old vnode is here:

https://github.com/domvm/domvm/blob/master/src/view/utils.js#L28
https://github.com/domvm/domvm/blob/master/src/view/patchAttrs.js#L53

you know what i'm gonna say, but i'll say it anyways: got a simple repro?

**Comment by lawrence-dol** [comment]
@Le

**Comment by lawrence-dol** [comment]
@lee

**Comment by lawrence-dol** [comment]
@leeoniya : You know what I'm going to reply, but I'll say it anyways... No repro yet, just fishing for direction at this point.

But the `patchAttrs` code makes me wonder... Text areas, of course, don't get their value from the `value` attribute, but from their content, in HTML, but in Javascript/DOM the value is stored in an attribute. My text area code looks like this:

````
function fieldTextArea(flddfn) {
    return gElm("textarea.field"+(flddfn.combine ? ".field-area" : ".field-wrap"),textFieldAttrs(flddfn,{
        onkeypress                      : textAreaKeys,
        }),flddfn.value());
    }
````

Might there be some subtle interaction for text areas that I'm forgetting?

**Comment by leeoniya** [comment]
> But the patchAttrs code makes me wonder... Text areas, of course, don't get their value from the value attribute, but from their content

...or the `.value` *property*.

as it turns out, domvm special-cases all the attrs in [1] to behave as if you did `{".value": "foo"}`, so it works fine: https://jsfiddle.net/3rs970vz/

[1] https://github.com/domvm/domvm/blob/master/src/view/utils.js#L28

**Comment by lawrence-dol** [comment]
Huh? I missed *that* memo. I'm heading out on vacation, so I'll pursue this further next week.

**Comment by lawrence-dol** [comment]
Still working on pinning this down, but it seems to be a problem with my code. I have confirmed that simply using `value` works perfectly well for text-areas and have switched to doing that.

**Comment by leeoniya** [comment]
should i leave this open or close and re-open if needed?

**Comment by lawrence-dol** [comment]
I'll close this and add some comments when I resolve the issue if it seems pertinent (or reopen it if I can show a problem in DOMVM).

**Comment by leeoniya** [comment]
thanks!
