### ISSUE TITLE
Fixed Structures

### ISSUE THREAD

**Issue by lawrence-dol** [domvm/domvm#215]
I have a good candidate for fixed structures in my emulation app, in that the main body of the display is a large table of either 80x24 or 132x27 cells. But it's not clear from the docs whether I can mark the table elements (table, tr, td) as fixed, as long as the key for the table changes when we switch from one to the other screen-size. Does the fixed structure need to be there for the lifespan on the app?

**Comment by leeoniya** [comment]
if you're referring to `FIXED_BODY`, then it should work okay. if the higher-level node gets destroyed/recreated, then it'll take everything with it as normal.

for your use-case, it may be even better to show the full 132x27 table with `FIXED_BODY` flags but gray out/add an inactive class to the unused cells when rendering 80x24. this way you avoid recreating the table entirely.
