### ISSUE TITLE
API Weakness - will/didRecycle

### ISSUE THREAD

**Issue by lawrence-dol** [domvm/domvm#216]
The `will/didRecycle` hooks take `oldNode,newNode` as arguments, but this prevents the same hook function from being used for all three Insert/Recycle/Reinsert functions, which functions are quite likely to want to do the same thing fairly often.

It would be better if the argument order was the opposite, though this ship has probably sailed.

My work-around is to use `(newNode,oldNode)` for `Recycle`, test for `oldNode` and do `newNode=oldNode` when I need the same node for all three.

**Comment by leeoniya** [comment]
> which functions are quite likely to want to do the same thing fairly often

this point is debatable. it's certainly not the case with the demo:

https://domvm.github.io/domvm/demos/playground/#lifecycle-hooks

> It would be better if the argument order was the opposite

do you mean uniform?

> though this ship has probably sailed

yeah.
