### ISSUE TITLE
Prevent iframe from reloading.

### ISSUE THREAD

**Issue by lawrence-dol** [domvm/domvm#217]
I have a view that renders an iframe. Once rendered the only thing that changes on the view is it's class property to add or remove a class which shows or hides the view. However, every time the view renders after being hidden, it reloads the iframe, causing the framed webpage to reset. The view is keyed, and the iframe is also keyed with "static".

The overall behavior is to click buttons on the screen, and show only the iframe linked to the button that was clicked, hiding the rest with "display: none". I have verified in the DOM that the hidden frames remain, but are greyed out. The hidden views are created once with `createView`, and injected using `injectView`. I was expecting that the entirely identical `iframe` would be left alone and that the key on it is entirely unnecessary.

Is this expected? If so, what's the right way to prevent it? (If not, I will, of course, need to create a fiddle to replicate the behavior.)

The view's vDOM is pretty trivial:

````
vDOM {
    "type":1,
    "flags":0,
    "attrs":{
        "class":"task-view"
    },
    "_class":"task-view",
    "tag":"div",
    "body":[{
        "type":1,
        "flags":0,
        "attrs":{
            "_key":"static",
            "src":"http://think.dolhub.com"
        },
        "tag":"iframe",
        "key":"static"
    }]
}
````

**Comment by leeoniya** [comment]
are you certain the views with the iframes are not getting re-mounted? there's no magic in domvm that's iframe-specific, so it should behave the same as raw DOM.

**Comment by lawrence-dol** [comment]
The blunder was mine; I forgot to remove some temporary code that was screwing things up and rendering a test view I'd dummied up instead of the intended one.
