### ISSUE TITLE
VNode holds old variable value on redraw

### ISSUE THREAD

**Issue by bfitzsimmons703** [domvm/domvm#219]
Hi @leeoniya! I'm running into an issue with values attached to node attributes. I find that, when a value is assigned to a node's `hooks` or `_data` attribute, the node holds the old value upon redraw, even though the value has been updated. It takes one more redraw (even when the value didn't change), to update correctly.

Here's my template, where `participant` is an object passed in from the view:

```
function Tile(participant) {
    console.log(`Outer: ${window.performance.now()} - ${participant.video}`);

    return el('.tile', [
        el('video', {
            autoPlay    : 1,
            playsInline : 1,
            key         : participant.session_id,
            _data       : {
                video : participant.video,
                local : participant.local
            }
        })
    ])
}
```

Notice that I log out `participant.video` (a boolean) in the second line, and assign it to a `_data` value on the node itself. 

When the view is redrawn with an updated `participant` object, the log on line 2 displays the correct boolean value, but when I log out the node itself, the `_data.video` value is still one step behind. You can see the logs here:

![Image of console logs](https://i.imgur.com/63kIrKM.jpg)

Notice that `participant.video` is `true` in the outer log, but `false` in the VNode's `_data` object (which is the third log line in the image above).

It logs correct boolean value on the next redraw, however, even when the `participant` object has not changed.

Any thoughts as to what is happening here? Thanks!

**Comment by leeoniya** [comment]
your code shows just a template function (it's not a "view" in domvm parlance). if you can provide a more complete example of jsfiddle that behaves this way, we can go from there.

**Comment by bfitzsimmons703** [comment]
Yep sorry, that would have been helpful. Will get a JSFiddle link up here shortly

**Comment by bfitzsimmons703** [comment]
Unfortunately the setup involves an API not open to the public yet, and creating a simplified version of the app in jsfiddle doesn't reproduce the issue. I clearly need to take a closer look at other components involved, so feel free to close this issue. Sorry about that!

**Comment by leeoniya** [comment]
no problem, if you get a repro feel free to re-open.
