### ISSUE TITLE
Question on vm.update

### ISSUE THREAD

**Issue by lesar** [domvm/domvm#223]
I have write an isomorphic app and have some problem understand vm.update:
the first show is do well but after if I update I have some trouble.  

here I hydrate and then update on stream map event:  
```javascript
const element = document.getElementById('root')

const vm = cv(App, { states, update, actions, comps, ssr: false })
vm.attach(element)

states.map(function (state) {
  logger.debug.log('pre redraw')
  vm.update({ states, update, actions, comps, ssr: false }, true)
  logger.debug.log('post redraw')
  return undefined
})
```
if states change `vm.update` was call with new data.  
App redraw is called well but inside App I have a sub view:  
```javascript
const App = function (vm) {
  return function (vm, { states, update, actions, comps, ssr }) {
    const state = states()
    const routing = Routing(state.route)
    const View = comps.getView(routing.localSegment.id)
    
    logger.debug.log(routing.localSegment.id, 'xxxxxxxxxxxxx routing.localSegment.id: __FN__')
    
    return vw(View, { states, update, actions, router, routing, comps })
  }
}
```
In state map cycle vm.update call redraw on App ... I see the log xxxxxxx...  
but seams that vw(View, data) inside App was not do the redraw: inside View I have put a log but nothing is logged  

have I misunderstand  vm.update or vw declaration?  

why vw is not call redraw on View?

best regards,  
Leonardo

**Comment by leeoniya** [comment]
domvm requires that every view returns an element node, e.g. `el("div", ...)`. you cannot directly return sub-views, nulls, or arrays.

does it work if you do this?

```js
return el("#app", [
  vw(View, { states, update, actions, router, routing, comps })
]);
```

**Comment by lesar** [comment]
Yes this is the problem: I have read that the view have to render a single node but I guess that if a view return a single element root it will behave like a node and so I have make it on return.  

Now I have enclose it in a div node and all work.  

best regards,  
Leonardo
