### ISSUE TITLE
Question on data inside View

### ISSUE THREAD

**Issue by lesar** [domvm/domvm#224]
I'm sorry: have a new question.  
Thank you @leeoniya in advantage for your answer and for your beautiful code on domvm.

In my code I call
```javascript
const vm = cv(App, { states, update, actions, comps, ssr: false })
vm.attach(element)
```
to hydrate a view.  
Inside it I have sub views.  
example: HeaderView  

```javascript
export const HeaderView = function (vm) {
  return function (vm, { states, update, actions, router, routing, comps }) {
    const { getView, isActiveMake } = comps
    const View = getView(routing.localSegment.id)
    const isActive = isActiveMake(View)

    logger.debug.log(routing.childSegment.id, 'routing.childSegment.id: __FN__') // <-------------- (*1)
    return el('section.hero.is-primary', [
       //.........
      , el('div', 'routing.childSegment.id: ' + routing.childSegment.id) // <-------------- (*2)
    ])
  }
}
```
rendering this view done by previous `vm.attach(element)` at hydration time, execute some my debug call on data passed to the view.  
The logger inside the view return function, marked in comment by (*1), log the update value of `routing` object  
but the render output show log value in the div element marked by (*2) a not update value of the same object routing.  

This not update value (a undef value) is the same that was at not hydtrated production:  
this is the call server side:
```javascript
    const content = cv(App, { states, update, actions, comps, ssr: true }).html() // <------(*3)
    // ...
    reply.code(200)
      .header('Content-Type', 'text/html; charset=utf-8')
      .send('<!DOCTYPE html>\n' + content)
```
at this time (*3) the `routing.childSegment.id` defined inside `App` was not defined and this is right

I studied your good code but I'm not be able to understand why.  

P.s.
the call to subview HeaderView is this:  
```javascript
export const ContattiView = function (vm) {
  return function (vm, { states, update, actions, router, routing, comps }) {
    return el('div', [
      vw(HeaderView, { states, update, actions, router, routing, comps })
      // .................................................
    ])
```

best regards,  
Leonardo

**Comment by lesar** [comment]
If I set a break point into (*2):  
```javascript
export const HeaderView = function (vm) {
  return function (vm, { states, update, actions, router, routing, comps }) {
    const { getView, isActiveMake } = comps
    const View = getView(routing.localSegment.id)
    const isActive = isActiveMake(View)

    logger.debug.log(routing.childSegment.id, 'routing.childSegment.id: __FN__') // <-------------- (*1)
    return el('section.hero.is-primary', [
       //.........
      , el('div', 'routing.childSegment.id: ' + routing.childSegment.id) // <-------------- (*2)
    ])
  }
}
```
and inside the breackpoint I read the content of `routing.childSegment.id` it show the right value  
but on browser is display an empty value:
```html
<div>routing.childSegment.id: </div>
```

**Comment by leeoniya** [comment]
it is difficult to understand the situation. please make a jsFiddle that shows the problem better. like this:

https://jsfiddle.net/yuLcskmv/

**Comment by lesar** [comment]
Thanks @leeoniya  I do some more debug first and if I have not good news I try to make an little example on jsfiddle.  
best regards,  
Leonardo

**Comment by lesar** [comment]
Debug is very complex so I have work on https://jsfiddle.net/4oc9rykj/1/  
This examples (thank you for original fiddle) work like my App: same bug.  

I guest that is not a bug, but is my misunderstand.  
I aspect that after  2 sec, the screen output have to change to show my message: 'Piro piro'
but nothing is changed on screen. 
What have I forget?  

best regards,  
Leonardo

best regards,
Leonardo

**Comment by leeoniya** [comment]
the main view constructor functions (App, Sub) only execute one time during view creation, so any state they receive will become outdated on any future updates.

you can solve this in couple ways:

1. only use arguments passed to `render()`, which are always get latest state: https://jsfiddle.net/t5m78nr4/
2. use a `willUpdate` hook to re-assign the state variable before each render: https://jsfiddle.net/dko3su05/
3. you can technically use `render()` to re-assign the state variable as well: https://jsfiddle.net/t897a6f0/
4. another way it to have a mutable state. and after mutating it, call `vm.redraw()` instead of `vm.update()`. this is the fastest, but maybe not nicest.

**Comment by leeoniya** [comment]
even another way is to use `vm.data`, which will be updated after `willUpdate` hook and before `render()`: https://jsfiddle.net/4ejwp9zy/

**Comment by lesar** [comment]
Thank you very much: the 4 solution are useful.  
My code on original project is like solution 1:  
> 1. only use arguments passed to render(), which are always get latest state: https://jsfiddle.net/t5m78nr4/  

I have not see (silly me) that in previous examples was used a param from view and not from the render.  
In my code I use render param but not work.  In your fiddle work. so there is a bug in my code.  
I check more and then I will let you know
best regards,  
Leonardo

**Comment by lesar** [comment]
## Solved
What happen  if ssr output is different from client attach?  
I guest nothing good.  

my url are like site.com/contatti#/rec
my idea was to make ssr output page like `site.com/contatti` and then  on click on a sub set of local hash url go to on url like `site.com/contatti#/rec` without have to do a new request to the server.  
In this manner work: first go on `site.com/contatti` then click on `site.com/contatti#/rec`   
but if I try to go direct to `site.com/contatti#/rec`  
mine app do this:  
first server output `site.com/contatti` to the client and then hydrate in client side... but in client side, my routing system, is aware of #/rec and output a different version of ssr.  

I have to find a way to make my routing system using only `site.com/contatti` before hydrate and `site.com/contatti#/rec` after:  
not easy.  

or I have to give up to use hash url like `site.com/contatti#/rec` to go on `site.com/contatti/rec`  
but this is my problem.  

thanks @leeoniya
