### ISSUE TITLE
unable to patch a node

### ISSUE THREAD

**Issue by doberkofler** [domvm/domvm#226]
I'm new to domvm and am having problems to understand how I can replace an existing node and all of it's children in domvm.

In the following example:

```javascript
const el = domvm.defineElement;
const cv = domvm.createView;

const inputNode =  el('input', {id: 'myId', type: 'text', placeholder: 'text'});
const buttonNode =  el('div', [el('button', {id: 'myId'}, 'push me')]);

const HelloView = function() {
	return function(vm) {
		return el('div', [el('div', [inputNode])]);
	};
};
const view = cv(HelloView);
view.mount(document.body);

inputNode.parent.patch(buttonNode);
view.redraw();
```

 I would have expected the node with the `input` element to be replaced with the `button` element, but this does not happen and I just get the following warning `FOREIGN_ELEMENT: domvm stumbled upon an element in its DOM that it didn't create, which may be problematic. You can inject external elements into the vtree using domvm.injectElement.`.

What is the correct way to remove/change/replace nodes in domvm?

**Comment by lawrence-dol** [comment]
Caveat: I've never needed to use patch, which is provided as an optimization. Rather I rebuild the entire vDOM every time and even with *very* complex UIs that's always been very good.

One trap is to remember that once you give some vDOM to DOMVM it now owns it and will mutate it according to what it needs. So you will need to change your constants to functions which return the fragment as a new object each time.

I suspect the error you are getting is because the two node objects are being mutated and the mutated object is passed again to DOMVM.

````js
const inputNode  =  () => { return el('input', {id: 'myId', type: 'text', placeholder: 'text'}); };
const buttonNode =  () => { return el('div', [el('button', {id: 'myId'}, 'push me')]); }

...

		return el('div', [el('div', [inputNode()])]);

...

inputNode.parent.patch(buttonNode());
````

It looks like you may already be using the developer package; if not switch to that an see if you get more information.

**Comment by doberkofler** [comment]
@lawrence-dol I have a very specific use case I'm trying to solve. I'm using a 3rd party library that itself uses domvm and must change/add something it the library. The library allows me to retrieve a domvm node that has been used to render it's content after rendering and I would need to modify/patch the node and force a re-render with my changes. In my sample code `inputNode` would be the node that I receive from the library and `buttonNode` the one that I would like to replace  `inputNode` with.

**Comment by lawrence-dol** [comment]
@doberkofler : I believe making the changes I suggest will probably resolve the problem. DOMVM will mutate those vDOM object you pass to it, so they need to be new objects each time. I got stung by this with my first app large enough to try caching and reusing vDOM objects. (The alternative would be for DOMVM to defensively clone the vDOM every time, and that would be hugely inefficient for the 99.9999% of the time that the objects are not retained by the app.)

**Comment by doberkofler** [comment]
I now changed my example based on your suggestion but still cannot seem to get `patch` working as I would have hoped for:

```javascript
const el = domvm.defineElement;
const cv = domvm.createView;

const buttonNode = text => el('div', [el('button', {id: 'myId'}, text)]);
const HelloView = function() {
	return function(vm) {
		return el('div', [
			el('div', [
				el('input', {id: 'myId', type: 'text', placeholder: 'text'})
			]),
			buttonNode('button#1'),
		]);
	};
};
const view = cv(HelloView);
view.mount(document.body);
const inputNode = view.node.body[0].body[0];
console.log({view, buttonNode, inputNode});
inputNode.parent.patch(buttonNode('button#1'), true);
view.redraw();
```

**Comment by lawrence-dol** [comment]
Try it without the id, or with a different ID for input and button. The ID will be used for a v-node key, which will prevent it from being altered if the same key is present.

If that doesn't work, you'll need to make a simple fiddle demonstrating the problem for @leeoniya to look into.

**Comment by doberkofler** [comment]
@leeoniya
I now reduced it to the bare minimum but it still does not seem to work. I guess, I did not understand how to `patch` or generally speaking how to modify an existing domvm model in the first place https://jsfiddle.net/s8h06uym/1/

```javascript
const el = domvm.defineElement;
const cv = domvm.createView;

const originalNode = el('div', [el('input', {id: 'input-id', type: 'text'})]);
const newNode = el('div', [el('button', {id: 'button-id'}, 'button')]);

const TestView = function() {
	return function(vm) {
		return originalNode;
	};
};
const view = cv(TestView);
view.mount(document.body);

const node = view.node;
console.log({view, node, originalNode, newNode});
node.patch(newNode, true);
view.redraw();
```

**Comment by lawrence-dol** [comment]
Your original node can’t be returned from the view — you need to return a completely new vDOM structure each time. Put that code as the return value of your render function. Ditto for the new node, make it a function that returns the vDOM fragment you want to patch. 

Once you pass some vDOM to DOMVM it owns that structure and your app must not reuse it. 

-- 
Lawrence Dol
(sent from my phone — please excuse typos and terseness.)

On Jun 26, 2021, at 22:57, Dieter Oberkofler ***@***.***> wrote:

﻿
@leeoniya
I now reduced it to the bare minimum but it still does not seem to work. I guess, I did not understand how to patch or generally speaking how to modify an existing domvm model in the first place https://jsfiddle.net/s8h06uym/1/

const el = domvm.defineElement;
const cv = domvm.createView;

const originalNode = el('div', [el('input', {id: 'input-id', type: 'text'})]);
const newNode = el('div', [el('button', {id: 'button-id'}, 'button')]);

const TestView = function() {
	return function(vm) {
		return originalNode;
	};
};
const view = cv(TestView);
view.mount(document.body);

const node = view.node;
console.log({view, node, originalNode, newNode});
node.patch(newNode, true);
view.redraw();

**Comment by lawrence-dol** [comment]
OK, I've had a look at your fiddle, and the DOMVM docs for patch, and I'm afraid I'm out of my depth here -- I'm not seeing from the docs how one would patch an existing, rendered DOM. We'll need to wait for @leeoniya to respond, and I'll learn something too. Sorry I couldn't be of any real help.

**Comment by doberkofler** [comment]
Thank you for all your help but I'm really confused now. I must be missing something very basic but cannot seem to get it.
I've now also tried the following but I still see no change:

```javascript
const el = domvm.defineElement;
const cv = domvm.createView;

const TestView = function() {
  return function(vm) {
    return el('div', [el('input', {id: 'input-id', type: 'text'})]);
  };
};
const view = cv(TestView);
view.mount(document.body);

const node = view.node;
console.log({view, node});
node.patch(el('div', [el('button', {id: 'button-id'}, 'button')]), true);
view.redraw();
```

**Comment by lawrence-dol** [comment]
@doberkofler : I know that @leeoniya is fairly busy right now with other projects, but my experience is that once you understand the intent it will be well designed and logical. Like you, though, I think we are missing something fundamental about how patch should be used.

Can you, perhaps, obviate the need to patch by altering the rendering to something like this:

````
let input = true;

const TestView = function() {
  return function(vm) {
    return (input
        ? el('div', [el('input', {id: 'input-id', type: 'text'})])
        : el('div', [el('button', {id: 'button-id'}, 'button')])
        );
  };
};
const view = cv(TestView);
view.mount(document.body);

input = false;
view.redraw();
````

This is how I do all my DOMVM views, with conditional output according to the current state of the program.

**Comment by doberkofler** [comment]
As I wrote, I have a very specific use case I'm trying to solve.
I'm using a 3rd party library that itself uses domvm and must inject some dom changes.
The library only allows me to retrieve a domvm node that has already been rendered and I would need to `patch` the node and it's children and force a re-render with my changes.

**Comment by leeoniya** [comment]
sorry, i'm on vacation. will look into this in next 48hrs.

**Comment by leeoniya** [comment]
as @lawrence-dol mentions, `patch()` is simply an optimization for mutating the dom, for example when you simply want to toggle the attributes or style of node without also going through the process of creating and diffing all the children. for example simply setting the visibility of a hidden tab to `hidden`.

it may help to look at the intended uses cases in the tests: https://github.com/domvm/domvm/blob/master/test/src/vnode-patch.js and the transitions demo: https://domvm.github.io/domvm/demos/playground/#lifecycle-hooks

there is an expectation that when/if the app re-renders, each view's `render()` returns a VNode that is matched to the actual dom when there are no changes. if you use patch() externally to mutate the dom, you still have no control over what the app will return in the next render() cycle. for this reason, i don't think you'll be able to properly keep your changes synced in a robust way.

**Comment by doberkofler** [comment]
@leeoniya Thank you for explaining.
Is it possible to maybe attach a hook (with patch or manually) so I can inject directly to the DOM after domvm has rendered?

**Comment by leeoniya** [comment]
you can try https://github.com/domvm/domvm#view-level

this replace any previously-attached `didRedraw` hook:

```js
vm.cfg({
  hooks: {
    didRedraw: (vm) => {
      // do stuff
    }
  }
});
```

**Comment by lawrence-dol** [comment]
@doberkofler : How did you fare with this? Can the issue be closed?

**Comment by doberkofler** [comment]
Yes, I found a workaround.
