### ISSUE TITLE
Cursor position lost when input value changed by app

### ISSUE THREAD

**Issue by lawrence-dol** [domvm/domvm#230]
Fiddle: https://jsfiddle.net/LawrenceDol/t9deL53f/

When I have an input which needs to be automatically formatted (e.g, uppercased), I attach an oninput handler and set the model value to `evt.target.value.toUpperCase()` and redraw. Doing this causes the cursor to jump to the end of the value upon insertion of a lowercase character anywhere in the input.

Obviously it's somehow bound up with the fact that when the redraw happens the value is changed. No visible change to the input element is shown by the browser (but browsers seem to no longer show input values in the inspection pane). I have tried changing the element value in the oninput handler as well, as currently shown in the fiddle.

I have found a workaround that *appears* to work, shown commented out in the fiddle code, but it will need to undergo full QA testing to be sure. (For more complex reformatting involving the insertion of characters, it will obviously need to determine how many characters were inserted by formatting before the insertion point and advanced the cursor location by that much.)

This seems to be a new behavior, happening in Firefox, Edge, Chrome, and Brave. I don't think it's caused by DOMVM per se, but I really need some insight into why this happens and how to avoid it. Right now the work-around is working for me in our product.

**Comment by leeoniya** [comment]
@lawrence-dol `help wanted` is usually used for "maintainers are looking for external help/contributions"

**Comment by leeoniya** [comment]
yeah, not really something uPlot can/should solve, as this is native behavior. the easiest solution here is the brain-dead one :)

https://jsfiddle.net/qf51L6rv/2/

```css
.value input {
  text-transform: uppercase;
}
```

```js
const el = domvm.defineElement;

let inputValue = "TESTVALUE";

const onInput = e => {
  inputValue = e.target.value.toUpperCase();
};

function AppView() {
  return function(vm) {
    return el("td.value", [
      el("input", {
        value: inputValue,
        oninput: onInput
      }),
    ]);
  };
}

let vm = domvm.createView(AppView).mount(document.body);
```
