### ISSUE TITLE
Make config return VM

### ISSUE THREAD

**Issue by lawrence-dol** [domvm/domvm#232]
Would it be possible to make `config` return the VM so this code:

````
let vm = domvm.createView(AppView).mount(document.body);
vm.config({ onevent: vmHandler });
````

could become the fluent:

````
let vm = domvm.createView(AppView)
              .config({ onevent: vmHandler })
              .mount(document.body);
````

I personally favor all setters in an API returning the object on which they operate.

**Comment by lawrence-dol** [comment]
See #239. Any objections to this?

**Comment by lawrence-dol** [comment]
@leeoniya : Is there any way I can help move this to a release?

**Comment by leeoniya** [comment]
merged
