### ISSUE TITLE
Bug with drainQueue

### ISSUE THREAD

**Issue by lawrence-dol** [domvm/domvm#238]
If a render function throws an exception when invoked via `drainQueue` future async renders are never triggered again. This occurs because the `rafId` is not reset until after all the render calls have been successfully run, and the exception aborts the entire function.

The most correct solution would seem to be to try/catch the render call:

````
try  { vm.redraw(true); } catch(err) { console.log("[DOMVM] Redraw Error:",err); }
````

Although it would be possible to move the `rafId = 0` to before the loop, that will then leave the `redrawQueue` uncleared, which will accumulate redraw requests, continually fail at the same faulting component, and it would also fail to invoke the `didRedraws` hooks.

Whether to silently fail or log is an orthogonal question. Given that this will always be a programming failure, it seems very incorrect to silently fail. One option is to log only for the developer package, but I personally would hate that as I almost never think to revert to that package until I've expended hours trying to find a bug.

Stack Trace (ironically the Firefox trace included async precursor traces and as a result the problem was actually much harder to understand):

![image](https://user-images.githubusercontent.com/8662551/153097154-e1fee389-9a4e-4b93-bd1b-cfa8f8df9027.png)

(@leeoniya -- explicitly tagging you, per request)

**Comment by lawrence-dol** [comment]
It's worth noting that an unhandled exception will be logged by the JS system, so I think it should log the error.

**Comment by leeoniya** [comment]
i've added you as a collaborator, feel free to make PR with proposed changes. a test for this scenario would also be helpful.

**Comment by lawrence-dol** [comment]
@leeoniya 

I'm working on this issue, and I have a problem with writing up the test. It seems like the tests need to use synchronous drawing, but this is by it's very nature an asynchronous test in `drainQueue`. 

While I could wrap `redrawSync` in a try/catch, it is arguably desirable to have the exception percolate through a synchronous redraw, only handling the asynchronous invocation. It's not clear to me how to test the asynchronous call with QUnit.

In my own code for a circumstance like this, I've monkey-patched the queuing function (in this case `requestAnimation`) with an inline invocation. But doing that in the test, though I can prove that the monkey-patch function is being used (with redrawSync = false), the exception is not caught.

I've pushed my work so far to branch `issue/#238-drain-queue`.

**Comment by leeoniya** [comment]
you should be able to add an async assertion from within something like a `didMount` or `didRedraw` hook to make sure the rendering cycle completed without crashing and burning: https://api.qunitjs.com/assert/async/

i've prototyped a different approach in 2 commits to https://github.com/domvm/domvm/tree/handle-render-exceptions

this will additionally render out any errors in the dom location of the view mounting point. it does require wrapping every supplied render function during initial view construction, so likely impacts performance to some extent. another common scenario it handles is exceptions in the view constructor.

thoughts?

**Comment by lawrence-dol** [comment]
@leeoniya : Your approach is equally viable, and catches more. My only concern would be whether the try/catch adds detectable overhead to `render()`. My main concern was stopping the exception from effectively halting the drainQueue processing, with minimal alterations.

**Comment by leeoniya** [comment]
avoiding try/catch used to be the boilerplate advice. however, JS engines have come pretty far since then and this is no longer true. at least when running the in-browser tests in this repo i see no performance difference in Chrome.

would be interested to see what you can measure in your app when using the code on this try/catch branch.

**Comment by lawrence-dol** [comment]
On my system, the difference is basically background noise. *Maybe* 100 to 200 us/render. My tests are an automated update (via `setTimeout(...,0)`) of a DOM structure of about 2000 nodes, where roughly 50% change on each render.

System: AMD 5900X Stock, RAM 64 GiB @ 3600GHz.
Browser: Firefox Developer Edition 98.0b5.

DOMVM 3.4.13:

![image](https://user-images.githubusercontent.com/8662551/154542459-cfc938ac-3b99-4a78-b104-9d605731369b.png)

handler-render-exceptions:

![image](https://user-images.githubusercontent.com/8662551/154543481-d4c542e1-9747-4ed2-ac97-d2e657e22dad.png)

**Comment by lawrence-dol** [comment]
I say go ahead with your fix, and then I'll close my pull request.

**Comment by lawrence-dol** [comment]
@leeoniya : Is there any way I can help move this to a release?

**Comment by lawrence-dol** [comment]
@leeoniya : And, I believe this fix is ready to go (your version of it, which is more comprehensive that mine).

**Comment by lawrence-dol** [comment]
@leeoniya : Ping!

**Comment by leeoniya** [comment]
merged my branch.
