### ISSUE TITLE
Backward Compatibility Bug from #235

### ISSUE THREAD

**Issue by lawrence-dol** [domvm/domvm#240]
It turns out that #235 introduced a backwards incompatibility; we forgot to revert the `node` argument to be the `target` node instead of the `currentTarget` node. We discussed this and decided to keep the node as what it's always been.

```
function handle(e) {
	let curTarg = e.currentTarget;
	let node = curTarg._node; // <== s/be e.target._node
```

(Related, though this might have been intentional, I see that `exec` is still calling the event handler with the `vm` bound as `this` instead of `currentTarget`; which is inconsistent with a normal event handler (and 
redundant since the vm is passed as an added argument.)

@leeoniya : How do you want to proceed?

**Comment by leeoniya** [comment]
yep, let's revert the `node` changes. but...

previously `handle()` was only used for delegated/parametrized events. and it had special behavior that bailed if you clicked on an element that lacked a `._node` (was not created by domvm, such as content populated via `{".innerHTML": "<button>Click me</button>"}`).

https://github.com/domvm/domvm/blob/f4586f7ea44e4368d6b668095f1cbbdd085f6a31/src/view/patchEvent.js#L61-L62

previously it was possibly simply by reverting to undecorated/function handlers that had no special logic, but now that all events are executed by `handle()`, is it okay to make it impossible to handle events (via delegation) originating from within third-party content?

**Comment by lawrence-dol** [comment]
That actually makes a _very powerful_ argument for the `node` to remain as the one to which the handler was attached. Then node is always non-null (else we wouldn't be handling the event).

At an app level this was trivially easy to rectify, in one of two ways. I could have used `evt.target._node`, or attached the event handler to the actual desired node; in this case I chose the latter.)

(Also BTW, I still feel strongly that the parameterized `exec` should use `fn.apply(e.currentTarget`, not `fn.apply(vm`. The latter constitutes a surprising value for `this` in an event handler).

**Comment by lawrence-dol** [comment]
Furthermore, I would personally be surprised to not be able to handle an event arising from some encapsulated third-party DOM using a handler attached to my DOMVM code. A key event is a key event... if it bubbles through my DOM I expect to be able to see it, capture, and take action upon it (regardless of whether my handler is parameterized or not). I would consider it a bug not to be able to do so.

**Comment by leeoniya** [comment]
so it sounds like we should just remove these lines, since they'll never do anything.

https://github.com/domvm/domvm/blob/7751b6331eac08282279b62ecc6966946ed67d5d/src/view/patchEvent.js#L26-L27

> (Also BTW, I still feel strongly that the parameterized exec should use fn.apply(e.currentTarget, not fn.apply(vm. The latter constitutes a surprising value for this in an event handler).

this removes any easy access to the vm from non-parameterized handlers. we _could_ instead pass `, node, vm, vm.data` here to have congruence with parameterized semantics:

https://github.com/domvm/domvm/blob/7751b6331eac08282279b62ecc6966946ed67d5d/src/view/patchEvent.js#L33-L34

i dont personally use `this` so have no strong attachment to its binding, but i _do_ want an easy route into the vdom from both types of handlers without having to resort to internal props like `e.currentTarget._node`.

**Comment by lawrence-dol** [comment]
Of course, at this point I've almost talked you into call `exec` for all handlers, so why not do that and inherit calling the onevent handlers and an explict false calling `preventDefault` as well?

**Comment by leeoniya** [comment]
well. i did originally want to leave bare event handlers as an optimization hatch that skipped all overhead so things like `mousemove` did not fire global handlers or allocate/concat new arg arrays at 60hz.

but i guess let's try it :)

**Comment by lawrence-dol** [comment]
OK, I am beginning to see why you originally agonized over this decision. 

Considering the principle of least surprise, I've talking myself back into having standard event handlers behave exactly like a normal JS event handler. I also want the programmer's expectations to be met if there appears to be nothing special about this handler, and for any the special stuff to be in play only if an array is used for the handler.

So, balancing consistency and PoLP, this PR continues to invoke a standard handler with the current target bound and the event as the only argument, and binds the current target to parameterized event handlers. Therefore:

  1. Standard event handlers are semantically identical to normal JS handlers.
  2. Parameterized handlers have a `this` consistent with standard and normal handlers.
  3. Simply wrapping a handler in `[]` opts into DOMVM enhancements, but requires no code changes to the existing handler unless it uses arguments other than the event.
  4. The node is the event target node, if defined (event arose from DOMVM element), or the handler node if not (event arose from non-DOMVM element).
  5. Wrapping a handler with brackets is effectively opting into DOMVM goodies (which I previously resisted, but with these changes find, particularly (2), to be the best balance).

The breaking change raised by this issue is thus resolved by (4), but one can still handle events arising from foreign DOM.

This proposal also fixes the remaining bug with `this` for parameterized handlers making it `currentTarget` in harmony with normal JS event handlers. Before 3.4.13, standard handlers were bound to `target`, and parameterized handlers were bound to `vm`. The former is just incorrect, and the latter is unnecessary because the `vm` is passed as an additional argument.

Lastly, I think the desire for "an easy route into the vdom from both types of handlers without having to resort to internal props" would be better met by a "findNode(elm)" API (on domvm?) which given an element finds the first node defined for that tree (and hence that node's VM). Equally, there is a good argument to be made for only getting access to the DOMVM vm and node if you use a parameterized event handler (and why not, since #235 removed all drawbacks associated with parameterized handlers?).

**Comment by lawrence-dol** [comment]
And I should note that the only performance penalty for standard event handlers is a couple of dereferences in `handle` plus the extra function call. 

This overhead could actually be removed with the current semantics and the unwrapped handler attached to the DOM element at no cost. There were other motivations for calling `handle()` for these, which we've since removed.

Change patchEvent to:

````
    if (nval == null)
        el[name] = null;
    else if (isFunc(nval))
        el[name] = nval;
    else if (oval == null)
        el[name] = handle;
````

**Comment by lawrence-dol** [comment]
@leeoniya : Any comments or objections to this?

**Comment by lawrence-dol** [comment]
Just notice this...

> this removes any easy access to the vm from non-parameterized handlers. we could instead pass , node, vm, vm.data here to have congruence with parameterized semantics:

Non-parameterized handlers have never had easy access to the `vm`. They were previously directly bound to the element and invoked with the event as their only argument. So this argument is moot; their semantics are identical after this PR, except they may be slightly more efficient because if the calling code generates a new function each time it doesn't have to removeListener/addListener since the listener is always patchEvent.handler, which get the current application handler from the VDOM when the event is triggered.

**Comment by lawrence-dol** [comment]
Speaking of easy access to the vm, that's where my utility function getVnode() comes in publicly. Given an element, get the nearest DOMVM node for it. I find myself reaching for `elm._node` far more often in my code that I would like. I would vastly prefer to alias vn to domvm.vnodeFor(elm) and use vn(elm).
