### ISSUE TITLE
Grammerly Safari extension breaks redraw

### ISSUE THREAD

**Issue by tropperstyle** [domvm/domvm#243]
This is very similar to #128

My unfortunate reality is that many of my users have this browser extension installed.

I ended up monkey-patching `removeChild(parEl, el)` to add the following line [here](https://github.com/domvm/domvm/blob/3.3.3/src/view/dom.js#L72):
```javascript
if (node === undefined) { return parEl.removeChild(el); }
```

This appears to suffice for my use-case, but someone with deeper knowledge of the internals might find a more thorough fix.

I dug a bit deeper, and it appears one of my recent app updates triggered this bug by using a `didUnmount` hook which triggers `setDeepRemove`

Here is a compact fiddle reproducing the issue and a screenshot from my live app:

https://jsfiddle.net/1r63csmu

<img width="2337" alt="Screen Shot 2022-03-02 at 2 44 03 PM" src="https://user-images.githubusercontent.com/28314/156636067-19f01c2d-c1c0-4955-bf23-8cfa05f35f86.png">

**Comment by leeoniya** [comment]
hey, @tropperstyle thanks for the thorough investigation, your fix LGTM. sorry for the delay!
