### ISSUE TITLE
Bad nodes in event handlers.

### ISSUE THREAD

**Issue by cornelius-dol** [domvm/domvm#245]
Recently, as my app has grown more complicated, I have been seeing uncaught exceptions in event handing at:

```
function handle(evt) {
	let elm = evt.currentTarget,
		dfn = elm._node.attrs["on" + evt.type];
                //        ^^^^^ -- TypeError: can't access property "attrs", e._node is undefined

	if (isArr(dfn)) {
```

I am pretty sure that these are race conditions with events that get delivered just after the DOMVM structure is torn down. I can't find any means in user-land to either handle or suppress them, and they are difficult to replicate, happening "occasionally" in production (where they are harmless, but look *really* ugly).

@leeoniya : Do you have any in-principle objection to adding a null check, either the modern `elm?._node...` or the older `elm._node && elm._node...`?

This seems inescapable in my case, where I have a controlling app loading other DOMVM apps in iframes, and the iframe can be closed at any time by the user, resulting in the framed app being torn down at any arbitrary moment.

**Comment by leeoniya** [comment]
i dont have an objection to it except that adding it might be just masking a deeper issue. would be good to actually understand what's going on and/or repro this reliably. does that check fix things in your case?

**Comment by cornelius-dol** [comment]
I'm investigating in between tasks, as time permits. Will be digging deeper on this over the next few weeks.

**Comment by cornelius-dol** [comment]
This is still active for me, just a very low priority. So far the data I have is pointing more and more to uncoordinated teardown of subcomponents.

**Comment by cornelius-dol** [comment]
It appears this was simply eliminated by blocking redraws as the app was being shutdown. I will return to this if I determine otherwise.
